### ISSUE TITLE
Issue with Bookmark Check

### ISSUE THREAD

**Issue by frosted13** [acquitelol/CutestBypass#11]
Hi,

I'm having a few issues. Whenever the bookmark check comes up gives an error.

![1000010034.png](https://github.com/acquitelol/azalea/assets/106967238/5d5c6bd2-bc2e-4bba-be03-bbc4b70f4758)

Few of my friends are also having this issue.

Thank you.

**Comment by frosted13** [comment]
Latest version

**Comment by acquitelol** [comment]
Is it possible to open the developer console and tell me any errors that appear when that message appears in Sparx? That message itself isn't very helpful of course, there are a million things that can go wrong, so an error from the console would be much appreciated.

Thank you!

**Comment by frosted13** [comment]
![image](https://github.com/acquitelol/azalea/assets/106967238/9a5cae9b-cda9-4afe-a137-6bcf3ac818a2)

**Comment by frosted13** [comment]
![image](https://github.com/acquitelol/azalea/assets/106967238/b716effd-c8f9-4254-a848-c1b3bc42ef21)

**Comment by frosted13** [comment]
It works sometimes then doesnt

**Comment by olifurz** [comment]
I also am having this issue. Seems to trigger at a bookmark check.

**Comment by acquitelol** [comment]
> ![image](https://user-images.githubusercontent.com/106967238/275953454-b716effd-c8f9-4254-a848-c1b3bc42ef21.png)

These aren't Azalea errors unfortunately. Look for any that say "bundle.js" or "React" or "Azalea" in them

**Comment by acquitelol** [comment]
If I had to guess I would assume you have malformed answers to bookwork checks from previous Azalea updates when the format for them was different. You can run `azalea.handlers.bookwork.clear()` to clear all stored codes or you can do `azalea.handlers.bookwork.list()` and see if there are any that don't look right (the format should be a bookwork code as a key and the value should have an id and an array of answers. If it doesn't, then something went wrong) after which you should be able to run `azalea.handlers.bookwork.delete("<code>")`.

This is most likely just the remaining artifacts of legacy bookwork codes which were stored before updates that changed the format, and because the format changed it fails to show them in the UI properly.

(Note that the format will not change again ever, unless some major improvement can be made)

**Comment by acquitelol** [comment]
Should be fixed in the newest release.
