### ISSUE TITLE
License enquiry and possible collaboration

### ISSUE THREAD

**Issue by BenMcAvoy** [acquitelol/CutestBypass#27]
I am working on a paid Sparx extension which I plan to open source soon (paid as the server that it connects to uses APIs that are payed, a self-hosted alternative will be provided) and was curious of two things:
1. I could get in contact with you
2. If we could either collaborate or that I could base the extension on your extension

I noticed you don't have any `LICENSE` files or some similar file so I would like to check with you before I do anything.

I am less familiar with React and like the way that your project is set out especially with how well it integrates into Sparx. I am contactable either through email at `ben.mcavoy@tutanota.com` or on Discord at `@benmcavoy_online`. Thanks!

**Comment by acquitelol** [comment]
Hi, thank you for your enquiry.

Unfortunately, I am not open to collaboration at the moment, due to GCSEs taking up most of my time.

The project currently has no `LICENSE` because the last time it *was* licensed someone stole the entire project and renamed it, claiming they wrote it themselves, with no credit to me or any reference to Azalea, and I had to go through several months of legal hell to take it down.

I think the best way to go about this to prevent the situation that happened before is the following:
- I will allow you to reference parts of Azalea's code while building your project
- You may **not** base the extension on Azalea

I'm very sorry for any inconveniences this may cause, I simply want to prevent history repeating itself. I hope you understand.

All the best,
- Rosie 💞

**Comment by BenMcAvoy** [comment]
Thanks for the quick response! I'm sorry to hear that people did that to your project. If you were to want to take it down under most OSS licenses they have to supply credit. Well, that's if you haven't already taken that action. 

Thank you so much for letting me reference some Azalea code, this will become ever useful.

 Are you in the UK? Simply curious as I am not aware if there are GCSEs in other countries (I'm in the UK and have them next year)

I wish you the best of luck in your exams! Thanks, Ben.

**Comment by acquitelol** [comment]
> If you were to want to take it down under most OSS licenses they have to supply credit. 

Yep, it was originally licensed under MIT. The people who stole the project did not include the original license nor any trace that the project belongs to me, so eventually I did get it taken down with a [DMCA takedown request](https://github.com/github/dmca/blob/a34ee149a76034917934b87ee046c1c96ef22749/2023/11/2023-11-10-azalea.md).

> Are you in the UK?

I do live in the UK! I'm currently in Year 11, hence my GCSEs started around the 10th of May.

> I wish you the best of luck in your exams!

Thank you!
